export const RUN_CHECK_MANAGED_EVIDENCE_DESCRIPTION_JA =
	"登録済みrepositoryで選択したcheck commandを実行します。checkKind=testではRun、active Verification Document、current inventory、保存済みmappingからcondition scope、evidence kind、runner、structured reporterをhostが解決し、同一testcaseの結果をmanaged evidenceとして保存します。通常はcommandとcheckKindだけを指定してください。Questionnaireで選択されていないtest種別は実行前に拒否します。TodoやRun statusは更新しません。";

export const COMPLETION_CHECK_ASSURANCE_DESCRIPTION_JA =
	"現在sourceのrequired conditionをtest inventory、明示mapping、同一testcaseのstructured execution、command gate、Project正本verifyから毎回再評価します。すべてsafe_passの場合だけ同一Run・Verification Documentにつき不変のEvidence Check Receiptを一度保存し、確認後の同一sourceに対するfollow-up verifyがPassすると完了可能です。未完了ならready=false、typed reason、suggestedAction、readinessDigestを返します。captureまたはidentity障害は再実行ではなくhost障害の報告を指示します。不足時はReceipt、Todo、Run statusを更新しません。";
