export const TEST_INVENTORY_TOOL_DESCRIPTION_JA =
	"登録済みrepositoryからactive test定義を収集し、inventoryId、sourceDigest、total、cursor、nextCursorと、inventory内限定の短いcaseKey、name、file、runnerを返します。必要に応じてrepository相対filePathsで絞り込み、同じfilePathsのままopaqueなnextCursorを指定して続きへ到達してください。sourceまたはfilePathsが変わったcursorはtyped failureになるため、先頭から再収集してください。各pageのinventoryIdは同じsource全体のinventoryを指すため、複数pageで集めたcaseKeyは最後のpageのinventoryIdとともにrecord_test_condition_mappingへ渡せます。runnerがunknownの場合はtest設定またはinventory scopeを修正して再収集してください。active discoveryに失敗したsupported runnerはtyped failureになります。test実行やTodo更新は行いません。";

export const TEST_EVIDENCE_MAPPING_TOOL_DESCRIPTION_JA =
	"collect_test_inventoryが返したinventoryIdとactive testのcaseKeyを、Verification Conditionへ完全一致でmappingします。表示名ではなくcaseKeyをそのまま指定してください。inventoryが現在のsourceと一致しない場合はtyped errorを返します。test実行やTodo更新は行いません。";
