export const TEST_INVENTORY_TOOL_DESCRIPTION_JA =
	"登録済みrepositoryからactive test定義を収集し、inventoryIdとinventory内限定の短いcaseKey、name、fileを返します。active discoveryに失敗したsupported runnerはtyped failureになります。test実行やTodo更新は行いません。Verification Conditionへ対応付ける場合は、同じ応答のinventoryIdとcaseKeyをrecord_test_condition_mappingへそのまま渡してください。";

export const TEST_EVIDENCE_MAPPING_TOOL_DESCRIPTION_JA =
	"collect_test_inventoryが返したinventoryIdとactive testのcaseKeyを、Verification Conditionへ完全一致でmappingします。表示名ではなくcaseKeyをそのまま指定してください。inventoryが現在のsourceと一致しない場合はtyped errorを返します。test実行やTodo更新は行いません。";
