import path from "node:path";
import { defineConfig } from "vitest/config";
import { testDatabasePath } from "./tests/vitest-db-env";

export default defineConfig({
	test: {
		globals: true,
		environment: "node",
		setupFiles: ["./tests/setup-vitest-db.ts"],
		env: {
			NODE_ENV: "test",
			DATABASE_URL: `file:${testDatabasePath}`,
			JWT_SECRET: "nightworkers-vitest-jwt-secret-with-enough-length",
			AUTH_MODE: "local",
			API_AUTH_REQUIRED: "false",
			APP_URL: "http://localhost:39174",
			CORS_ORIGIN: "http://localhost:39174",
			NIGHTWORKERS_DESKTOP: "0",
		},
		fileParallelism: false,
		globalSetup: ["./tests/global-cleanup-after-tests.ts"],
		include: ["tests/**/*.{test,spec}.{ts,tsx}"],
		exclude: ["tests/e2e/**", "tests/live/**"],
		coverage: {
			provider: "v8",
			reporter: ["text", "html", "lcov", "json-summary"],
			reportsDirectory: "./coverage-backend",
			include: ["api/**/*.ts", "shared/**/*.ts"],
			exclude: [
				"**/*.d.ts",
				"api/index.ts",
				"api/server.ts",
				"api/mcp/**",
				"api/services/runner/**",
				"api/scripts/**",
				"api/db/seed.ts",
				"api/db/migrations/**",
				"api/db/schema.ts",
				"api/db/client.ts",
				"api/app.ts",
				"api/config.ts",
				"api/db/retry.ts",
				"api/**/*.schema.ts",
				"shared/**/*.schema.ts",
				"api/db/**/*schema.ts",
				"api/**/*.routes.ts",
				"api/routes/*.ts",
				"api/services/realtime/nightworkers-ws.ts",
				"api/services/structured-generation/prompts/*.ts",
				"api/db/**",
				"api/**/*.repository.ts",
				"api/modules/**/routes/**",
				"api/modules/**/*routes.ts",
				"api/modules/**/*route*.ts",
				"api/modules/**/*handlers.ts",
				"api/modules/questionnaire/**",
				"api/modules/planViews/**",
				"api/modules/project-evaluation/**",
				"api/modules/project-detail/**",
				"api/modules/mission-planner/**",
				"**/*.test.{ts,tsx}",
				"**/*.spec.{ts,tsx}",
				"tests/**",
			],
		},
		alias: {
			"@": path.resolve(__dirname, "./src"),
			"@api": path.resolve(__dirname, "./api"),
		},
	},
});
