import path from "node:path";
import { defineConfig } from "vitest/config";
import { testDatabasePath } from "./tests/vitest-db-env";

export default defineConfig({
	test: {
		globals: true,
		environment: "node",
		setupFiles: ["./tests/setup-vitest-db.ts"],
		env: {
			NODE_ENV: "test",
			DATABASE_URL: `file:${testDatabasePath}`,
			JWT_SECRET: "nightworkers-vitest-jwt-secret-with-enough-length",
			AUTH_MODE: "local",
			API_AUTH_REQUIRED: "false",
			APP_URL: "http://localhost:39174",
			CORS_ORIGIN: "http://localhost:39174",
			NIGHTWORKERS_DESKTOP: "0",
		},
		fileParallelism: false,
		globalSetup: ["./tests/global-cleanup-after-tests.ts"],
		include: ["tests/**/*.{test,spec}.{ts,tsx}"],
		exclude: ["tests/e2e/**", "tests/live/**"],
		coverage: {
			provider: "v8",
			reporter: ["text", "html", "lcov", "json-summary"],
			reportsDirectory: "./coverage",
			include: [
				"api/**/*.ts",
				"shared/**/*.ts",
				"src/modules/nightworkers/workbenchSelectors.ts",
				"src/lib/utils.ts",
			],
			exclude: [
				"**/*.d.ts",
				"api/services/oauth/base.ts",
				"api/index.ts",
				"api/server.ts",
				"api/mcp/**",
				"api/services/runner/**",
				"api/scripts/**",
				"api/db/seed.ts",
				"api/db/migrations/**",
				"api/db/schema.ts",
				"api/db/client.ts",
				"api/app.ts",
				"api/config.ts",
				"api/db/retry.ts",
				"api/modules/blueprint/blueprint.service.ts",
				"api/modules/dataModel/data-model.service.ts",
				"api/modules/specification/specification.service.ts",
				"api/services/llm-usage/index.ts",
				"api/services/blueprints/blueprint-catalog/index.ts",
				"api/services/mcp/**",
				"api/services/quality/**",
				"api/services/overview/**",
				"api/services/pricing/**",
				"api/**/*.schema.ts",
				"shared/**/*.schema.ts",
				"api/db/**/*schema.ts",
				"api/**/*.routes.ts",
				"api/routes/*.ts",
				"api/services/quality/coverage-autonomy-gate.ts",
				"api/services/realtime/nightworkers-ws.ts",
				"api/services/structured-generation/prompts/*.ts",
				"api/services/overview/index.ts",
				"api/services/pricing/index.ts",
				"src/routeTree.gen.ts",
				"src/mocks/**",
				"**/*.test.{ts,tsx}",
				"**/*.spec.{ts,tsx}",
				"tests/**",
				"scripts/**",
				"dist/**",
				"dist-api/**",
				"dist-api-desktop/**",
				"node_modules/**",
			],
		},
		alias: {
			"@": path.resolve(__dirname, "./src"),
			"@api": path.resolve(__dirname, "./api"),
		},
	},
});
