/* eslint-disable */
/**
 * AUTO-GENERATED FILE.
 * Source: ./designSystem.pen
 * Run: pnpm -C designSystem pencil:variants
 */

export type PenVariantIndex = Record<string, string[]>;

export const penVariantIndex: PenVariantIndex = {
  Accordion: ['Default', 'Open'],
  'Accordion.test': ['Default'],
  Alert: ['Default', 'Destructive', 'Info', 'Success', 'Warning'],
  'Alert.test': ['Default'],
  Avatar: ['Default', 'Text'],
  'Avatar.test': ['Default'],
  Badge: ['Default', 'Destructive', 'Outline', 'Secondary'],
  'Badge.test': ['Default'],
  Breadcrumb: ['Current', 'Default', 'Ellipsis', 'Separator'],
  'Breadcrumb.test': ['Default'],
  BreadcrumbItem: ['Current', 'Ellipsis', 'Separator'],
  Button: [
    'Default',
    'Destructive',
    'Ghost',
    'Info',
    'Large/Default',
    'Large/Destructive',
    'Large/Ghost',
    'Large/Outline',
    'Large/Secondary',
    'Outline',
    'Secondary',
    'Success',
    'Warning',
  ],
  'Button.test': ['Default'],
  Card: ['Default'],
  'Card.test': ['Default'],
  Checkbox: ['Checked', 'Default'],
  'Checkbox.test': ['Default'],
  Combobox: ['Default'],
  'Combobox.test': ['Default'],
  DataTable: ['Default'],
  'DataTable.test': ['Default'],
  Dialog: ['Default'],
  'Dialog.test': ['Default'],
  DropdownMenu: ['Default'],
  'DropdownMenu.test': ['Default'],
  Icon: ['Chevron-right', 'Dots'],
  IconButton: ['Default', 'Destructive', 'Outline', 'Secondary'],
  'IconButton.test': ['Default'],
  Input: ['Default'],
  'Input.test': ['Default'],
  InputGroup: ['Default'],
  'InputGroup.test': ['Default'],
  InputOtp: ['Default'],
  'InputOtp.test': ['Default'],
  InputOTPGroup: ['Default'],
  Label: ['Default'],
  'Label.test': ['Default'],
  List: ['Checked', 'Default', 'Filled'],
  'List.test': ['Default'],
  ListItem: ['Checked'],
  ListSearchBox: ['Filled'],
  Modal: ['Default'],
  'Modal.test': ['Default'],
  Pagination: ['Default'],
  'Pagination.test': ['Default'],
  PaginationItem: ['Active', 'Ellipsis'],
  Progress: ['Default'],
  'Progress.test': ['Default'],
  Radio: ['Default', 'Selected'],
  'Radio.test': ['Default'],
  RadioGroup: ['Default', 'Selected'],
  'RadioGroup.test': ['Default'],
  Select: ['Default'],
  'Select.test': ['Default'],
  SelectGroup: ['Default'],
  Separator: ['Default'],
  'Separator.test': ['Default'],
  Sidebar: ['Active', 'Default'],
  'Sidebar.test': ['Default'],
  SidebarItem: ['Active'],
  Switch: ['Checked', 'Default'],
  'Switch.test': ['Default'],
  TabItem: ['Active'],
  Table: ['Default'],
  'Table.test': ['Default'],
  Tabs: ['Default'],
  'Tabs.test': ['Default'],
  Textarea: ['Default'],
  'Textarea.test': ['Default'],
  TextareaGroup: ['Default'],
  Tooltip: ['Default'],
  'Tooltip.test': ['Default'],
};

export const penVariantMeta = {
  sourceVersion: '2.9',
  totalComponents: 72,
  totalVariants: 110,
} as const;
