import { AppError } from "../../lib/errors";

export type MissionPilotErrorCode =
	| "MISSION_PILOT_SOURCE_NOT_FOUND"
	| "MISSION_PILOT_SOURCE_ALREADY_TASKED"
	| "MISSION_PILOT_SOURCE_REPOSITORY_MISMATCH"
	| "MISSION_PILOT_INITIAL_PROMPT_REQUIRED"
	| "MISSION_PILOT_CREATE_CONFLICT"
	| "MISSION_PILOT_NOT_FOUND"
	| "MISSION_PILOT_ALREADY_PLAYING"
	| "MISSION_PILOT_VERSION_CONFLICT"
	| "MISSION_PILOT_INTAKE_FAILED";

export class MissionPilotError extends AppError {}
