import { AppError } from "../../lib/errors";

export type MissionPilotErrorCode =
	| "MISSION_PILOT_INITIAL_PROMPT_REQUIRED"
	| "MISSION_PILOT_INTEGRITY_ERROR"
	| "MISSION_PILOT_LEGACY_ENDPOINT_RETIRED"
	| "MISSION_PILOT_NOT_FOUND"
	| "MISSION_PILOT_ALREADY_PLAYING"
	| "MISSION_PILOT_VERSION_CONFLICT"
	| "MISSION_PILOT_INTAKE_FAILED"
	| "MISSION_PILOT_PLAN_INTAKE_NEEDS_EDIT"
	| "MISSION_PILOT_PRE_QUEUE_TASK_TERMINAL"
	| "MISSION_PILOT_PRE_QUEUE_UNEXPECTED_RUN"
	| "MISSION_PILOT_QUEUE_HANDOFF_STALE_CONTEXT"
	| "MISSION_PILOT_QUEUE_HANDOFF_EVIDENCE_MISSING"
	| "MISSION_PILOT_QUEUE_HANDOFF_DUPLICATE";

export class MissionPilotError extends AppError {}
