const KNOWN_ACTIVITY_KINDS = new Set([
	"user.message",
	"assistant.delta",
	"assistant.message",
	"assistant.pause",
	"assistant.resume",
	"assistant.raw_output",
	"llm.request",
	"llm.response_delta",
	"llm.response_final",
	"llm.decision_json",
	"llm.schema_result",
	"llm.error",
	"llm.usage",
	"llm.provider_activity",
	"runtime.decision",
	"runtime.state",
	"tool.call",
	"tool.result",
	"tool.error",
	"command.output",
	"file.diff",
	"file.patch",
	"file.write",
	"verification.output",
	"run.status",
	"todo.status",
	"transport.subscribe",
	"transport.replay",
	"transport.publish",
	"ui.optimistic",
	"system.info",
	"system.error",
	"unknown.activity",
]);

export function normalizeActivityKind(kind: string) {
	return KNOWN_ACTIVITY_KINDS.has(kind) ? kind : "unknown.activity";
}
