import { z } from "@hono/zod-openapi";

const runEventTypeSchema = z.enum([
	"run.created",
	"run.prompt_prepared",
	"run.runtime_started",
	"run.runtime_finished",
	"run.outcome_decided",
	"run.finalizing_started",
	"run.final_judgment_created",
	"run.recovered",
	"turn.started",
	"turn.finished",
	"model.request_started",
	"model.retry_scheduled",
	"model.retry_started",
	"model.response_delta",
	"model.response_finished",
	"model.response_repaired",
	"model.response_parse_failed",
	"supervisor.decision",
	"tool.call_started",
	"tool.call_progress",
	"tool.call_finished",
	"tool.policy_blocked",
	"hook.started",
	"hook.finished",
	"hook.blocked",
	"hook.failed",
	"verification.started",
	"verification.finished",
	"git.status_collected",
	"git.diff_collected",
	"git.closeout_committed",
	"git.closeout_commit_failed",
	"git.closeout_pushed",
	"git.closeout_push_failed",
	"safety.budget_reached",
	"safety.policy_violation",
	"safety.repeated_failure",
	"human.review_submitted",
	"review.rubric_loaded",
	"review.evaluation_started",
	"review.llm_started",
	"review.llm_finished",
	"review.evaluation_finished",
	"review.session_auto_started",
	"review.required_section_auto_started",
	"review.required_section_auto_failed",
	"workbench.session.created",
	"workbench.session.queued",
	"workbench.session.run_requested",
	"workbench.artifact.created",
	"workbench.review.followup_requested",
	"workbench.learning.capture_requested",
	"system.info",
	"system.warning",
	"system.error",
]);

const runEventSeveritySchema = z.enum([
	"debug",
	"info",
	"warning",
	"error",
	"checkpoint",
]);
const runEventActorSchema = z.enum([
	"system",
	"runtime",
	"supervisor",
	"worker",
	"tool",
	"verifier",
	"human",
]);

export const runEventSchema = z.object({
	version: z.literal(1),
	id: z.string().uuid().optional(),
	runId: z.string().uuid(),
	taskId: z.string().uuid().optional(),
	seq: z.number().int().optional(),
	timestamp: z.string(),
	type: runEventTypeSchema,
	severity: runEventSeveritySchema,
	actor: runEventActorSchema,
	message: z.string(),
	data: z.record(z.string(), z.unknown()).optional(),
});

export const runEventJsonlLineSchema = z.discriminatedUnion("type", [
	z.object({
		type: z.literal("nightworkers_run"),
		version: z.literal(1),
		runId: z.string().uuid(),
		taskId: z.string().uuid(),
		repositoryId: z.string().uuid().nullable().optional(),
		createdAt: z.string(),
		cwd: z.string().nullable().optional(),
		workerKind: z.string().nullable().optional(),
		exportedAt: z.string(),
	}),
	z.object({
		type: z.literal("run_event"),
		version: z.literal(1),
		runId: z.string().uuid(),
		seq: z.number().int(),
		event: runEventSchema,
		reviewResult: z.unknown().optional(),
	}),
	z.object({
		type: z.literal("run_summary"),
		version: z.literal(1),
		runId: z.string().uuid(),
		status: z.string(),
		summary: z.string().nullable().optional(),
		finalReport: z.string().nullable().optional(),
		finalJudgment: z.unknown().nullable().optional(),
		todos: z
			.array(
				z.object({
					id: z.string().uuid(),
					seq: z.number().int(),
					title: z.string(),
					taskType: z.string(),
					status: z.string(),
					procedureId: z.string().nullable().optional(),
					statusReason: z.string().nullable().optional(),
					completionGateResult: z.unknown().nullable().optional(),
				}),
			)
			.optional(),
		diffBytes: z.number().int(),
		eventCount: z.number().int(),
	}),
]);
