import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { config as loadEnv } from "dotenv";
import { requireMaintenanceDatabaseAccess } from "../../shared/runtime-database-access.mjs";

loadEnv({ quiet: true });
requireMaintenanceDatabaseAccess(process.env);

const DEFAULT_SNAPSHOT_NAME = "current";
const SQLITE_BUFFER_SIZE = 512 * 1024 * 1024;

type SqliteTableInfoRow = {
	name: string;
};

function resolveSnapshotName() {
	const args = process.argv.slice(2);
	if (args.length === 0) return DEFAULT_SNAPSHOT_NAME;
	if (args.length === 1) return normalizeSnapshotName(args[0]);
	if (args.length === 2 && args[0] === "--snapshot") {
		return normalizeSnapshotName(args[1]);
	}
	throw new Error(
		"Usage: bun api/scripts/dump-current-state.ts [current|cond1|...|cond8]",
	);
}

function normalizeSnapshotName(name: string) {
	if (name === "current" || /^cond[1-8]$/.test(name)) return name;
	throw new Error(
		`Unknown DB snapshot "${name}". Expected current or cond1 through cond8.`,
	);
}

function resolveSnapshotPath(snapshotName: string) {
	const relativePath =
		snapshotName === "current"
			? "drizzle/seeds/current-state.sql"
			: `drizzle/seeds/conditions/${snapshotName}.sql`;
	return path.resolve(process.cwd(), relativePath);
}

function resolveDatabasePath() {
	const databaseUrl = process.env.DATABASE_URL?.trim();
	if (!databaseUrl) {
		throw new Error("DATABASE_URL is required");
	}
	if (
		databaseUrl.startsWith("libsql:") ||
		databaseUrl.startsWith("http:") ||
		databaseUrl.startsWith("https:")
	) {
		throw new Error(
			`db:dump:current only supports local SQLite files. Received DATABASE_URL=${databaseUrl}`,
		);
	}
	const rawPath = databaseUrl.startsWith("file:")
		? databaseUrl.slice("file:".length)
		: databaseUrl;
	return path.resolve(process.cwd(), rawPath);
}

function quoteIdentifier(identifier: string) {
	return `"${identifier.replaceAll('"', '""')}"`;
}

function queryJson<T>(databasePath: string, sql: string): T[] {
	const output = execFileSync("sqlite3", ["-json", databasePath, sql], {
		encoding: "utf8",
		maxBuffer: SQLITE_BUFFER_SIZE,
	});
	return JSON.parse(output) as T[];
}

function loadColumnLists(databasePath: string) {
	const tables = queryJson<{ name: string }>(
		databasePath,
		"SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
	);
	const columnsByTable = new Map<string, string>();
	for (const table of tables) {
		const columns = queryJson<SqliteTableInfoRow>(
			databasePath,
			`PRAGMA table_info(${quoteIdentifier(table.name)})`,
		).map((column) => quoteIdentifier(column.name));
		columnsByTable.set(table.name, columns.join(", "));
	}
	return columnsByTable;
}

function buildSnapshotSql(databasePath: string, snapshotName: string) {
	execFileSync("sqlite3", [databasePath, "PRAGMA wal_checkpoint(FULL);"], {
		stdio: "ignore",
	});
	const columnsByTable = loadColumnLists(databasePath);
	const dump = execFileSync("sqlite3", [databasePath, ".dump --data-only"], {
		encoding: "utf8",
		maxBuffer: SQLITE_BUFFER_SIZE,
	});
	const insertLines = dump
		.split(/\r?\n/)
		.map((line) => line.trimEnd())
		.flatMap((line) => {
			const match = /^INSERT INTO "?([^"\s]+)"? VALUES/.exec(line);
			if (!match) return [];
			const table = match[1];
			const columns = columnsByTable.get(table);
			if (!columns) return [];
			return line.replace(
				/^INSERT INTO ("?[^"\s]+"?) VALUES/,
				`INSERT INTO ${quoteIdentifier(table)} (${columns}) VALUES`,
			);
		});
	const timestamp = new Date().toISOString();
	return [
		`-- Snapshot "${snapshotName}" of SQLite state as of ${timestamp}`,
		"-- Generated by bun run db:dump:current or db:dump:condN",
		...insertLines,
		"",
	].join("\n");
}

function main() {
	const snapshotName = resolveSnapshotName();
	const databasePath = resolveDatabasePath();
	const snapshotPath = resolveSnapshotPath(snapshotName);
	const snapshotSql = buildSnapshotSql(databasePath, snapshotName);
	mkdirSync(path.dirname(snapshotPath), { recursive: true });
	writeFileSync(snapshotPath, snapshotSql, "utf8");
	console.log(
		`Dumped DB snapshot "${snapshotName}" from ${databasePath} to ${snapshotPath}`,
	);
}

main();
