import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import path from "node:path";
import { config as loadEnv } from "dotenv";

loadEnv({ quiet: true });

const SNAPSHOT_RELATIVE_PATH = "drizzle/seeds/current-state.sql";
const SQLITE_BUFFER_SIZE = 512 * 1024 * 1024;

type SqliteTableInfoRow = {
	name: string;
};

function resolveDatabasePath() {
	const databaseUrl = process.env.DATABASE_URL?.trim();
	if (!databaseUrl) {
		throw new Error("DATABASE_URL is required");
	}
	if (
		databaseUrl.startsWith("libsql:") ||
		databaseUrl.startsWith("http:") ||
		databaseUrl.startsWith("https:")
	) {
		throw new Error(
			`db:dump:current only supports local SQLite files. Received DATABASE_URL=${databaseUrl}`,
		);
	}
	const rawPath = databaseUrl.startsWith("file:")
		? databaseUrl.slice("file:".length)
		: databaseUrl;
	return path.resolve(process.cwd(), rawPath);
}

function quoteIdentifier(identifier: string) {
	return `"${identifier.replaceAll('"', '""')}"`;
}

function queryJson<T>(databasePath: string, sql: string): T[] {
	const output = execFileSync("sqlite3", ["-json", databasePath, sql], {
		encoding: "utf8",
		maxBuffer: SQLITE_BUFFER_SIZE,
	});
	return JSON.parse(output) as T[];
}

function loadColumnLists(databasePath: string) {
	const tables = queryJson<{ name: string }>(
		databasePath,
		"SELECT name FROM sqlite_master WHERE type = 'table' AND name NOT LIKE 'sqlite_%' ORDER BY name",
	);
	const columnsByTable = new Map<string, string>();
	for (const table of tables) {
		const columns = queryJson<SqliteTableInfoRow>(
			databasePath,
			`PRAGMA table_info(${quoteIdentifier(table.name)})`,
		).map((column) => quoteIdentifier(column.name));
		columnsByTable.set(table.name, columns.join(", "));
	}
	return columnsByTable;
}

function buildSnapshotSql(databasePath: string) {
	execFileSync("sqlite3", [databasePath, "PRAGMA wal_checkpoint(FULL);"], {
		stdio: "ignore",
	});
	const columnsByTable = loadColumnLists(databasePath);
	const dump = execFileSync("sqlite3", [databasePath, ".dump --data-only"], {
		encoding: "utf8",
		maxBuffer: SQLITE_BUFFER_SIZE,
	});
	const insertLines = dump
		.split(/\r?\n/)
		.map((line) => line.trimEnd())
		.flatMap((line) => {
			const match = /^INSERT INTO "?([^"\s]+)"? VALUES/.exec(line);
			if (!match) return [];
			const table = match[1];
			const columns = columnsByTable.get(table);
			if (!columns) return [];
			return line.replace(
				/^INSERT INTO ("?[^"\s]+"?) VALUES/,
				`INSERT INTO ${quoteIdentifier(table)} (${columns}) VALUES`,
			);
		});
	const timestamp = new Date().toISOString();
	return [
		`-- Snapshot of current SQLite state as of ${timestamp}`,
		"-- Generated by bun run db:dump:current",
		...insertLines,
		"",
	].join("\n");
}

function main() {
	const databasePath = resolveDatabasePath();
	const snapshotPath = path.resolve(process.cwd(), SNAPSHOT_RELATIVE_PATH);
	const snapshotSql = buildSnapshotSql(databasePath);
	writeFileSync(snapshotPath, snapshotSql, "utf8");
	console.log(
		`Dumped current DB snapshot from ${databasePath} to ${snapshotPath}`,
	);
}

main();
