/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShowcaseRouteImport } from './routes/showcase'
import { Route as RepositoriesRouteImport } from './routes/repositories'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BbsIndexRouteImport } from './routes/bbs/index'
import { Route as TasksIdRouteImport } from './routes/tasks.$id'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as BbsIdRouteImport } from './routes/bbs/$id'

const ShowcaseRoute = ShowcaseRouteImport.update({
  id: '/showcase',
  path: '/showcase',
  getParentRoute: () => rootRouteImport,
} as any)
const RepositoriesRoute = RepositoriesRouteImport.update({
  id: '/repositories',
  path: '/repositories',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BbsIndexRoute = BbsIndexRouteImport.update({
  id: '/bbs/',
  path: '/bbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksIdRoute = TasksIdRouteImport.update({
  id: '/tasks/$id',
  path: '/tasks/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BbsIdRoute = BbsIdRouteImport.update({
  id: '/bbs/$id',
  path: '/bbs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
  '/showcase': typeof ShowcaseRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bbs/': typeof BbsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
  '/showcase': typeof ShowcaseRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bbs': typeof BbsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/repositories': typeof RepositoriesRoute
  '/showcase': typeof ShowcaseRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/tasks/$id': typeof TasksIdRoute
  '/bbs/': typeof BbsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/repositories'
    | '/showcase'
    | '/bbs/$id'
    | '/oauth/callback'
    | '/tasks/$id'
    | '/bbs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/repositories'
    | '/showcase'
    | '/bbs/$id'
    | '/oauth/callback'
    | '/tasks/$id'
    | '/bbs'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/repositories'
    | '/showcase'
    | '/bbs/$id'
    | '/oauth/callback'
    | '/tasks/$id'
    | '/bbs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RepositoriesRoute: typeof RepositoriesRoute
  ShowcaseRoute: typeof ShowcaseRoute
  BbsIdRoute: typeof BbsIdRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  TasksIdRoute: typeof TasksIdRoute
  BbsIndexRoute: typeof BbsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/showcase': {
      id: '/showcase'
      path: '/showcase'
      fullPath: '/showcase'
      preLoaderRoute: typeof ShowcaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/repositories': {
      id: '/repositories'
      path: '/repositories'
      fullPath: '/repositories'
      preLoaderRoute: typeof RepositoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbs/': {
      id: '/bbs/'
      path: '/bbs'
      fullPath: '/bbs/'
      preLoaderRoute: typeof BbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks/$id': {
      id: '/tasks/$id'
      path: '/tasks/$id'
      fullPath: '/tasks/$id'
      preLoaderRoute: typeof TasksIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbs/$id': {
      id: '/bbs/$id'
      path: '/bbs/$id'
      fullPath: '/bbs/$id'
      preLoaderRoute: typeof BbsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RepositoriesRoute: RepositoriesRoute,
  ShowcaseRoute: ShowcaseRoute,
  BbsIdRoute: BbsIdRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  TasksIdRoute: TasksIdRoute,
  BbsIndexRoute: BbsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
