/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BbsIndexRouteImport } from './routes/bbs/index'
import { Route as OauthCallbackRouteImport } from './routes/oauth.callback'
import { Route as BbsIdRouteImport } from './routes/bbs/$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BbsIndexRoute = BbsIndexRouteImport.update({
  id: '/bbs/',
  path: '/bbs/',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthCallbackRoute = OauthCallbackRouteImport.update({
  id: '/oauth/callback',
  path: '/oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BbsIdRoute = BbsIdRouteImport.update({
  id: '/bbs/$id',
  path: '/bbs/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/bbs/': typeof BbsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/bbs': typeof BbsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/bbs/$id': typeof BbsIdRoute
  '/oauth/callback': typeof OauthCallbackRoute
  '/bbs/': typeof BbsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/bbs/$id' | '/oauth/callback' | '/bbs/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/bbs/$id' | '/oauth/callback' | '/bbs'
  id: '__root__' | '/' | '/login' | '/bbs/$id' | '/oauth/callback' | '/bbs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  BbsIdRoute: typeof BbsIdRoute
  OauthCallbackRoute: typeof OauthCallbackRoute
  BbsIndexRoute: typeof BbsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbs/': {
      id: '/bbs/'
      path: '/bbs'
      fullPath: '/bbs/'
      preLoaderRoute: typeof BbsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/callback': {
      id: '/oauth/callback'
      path: '/oauth/callback'
      fullPath: '/oauth/callback'
      preLoaderRoute: typeof OauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bbs/$id': {
      id: '/bbs/$id'
      path: '/bbs/$id'
      fullPath: '/bbs/$id'
      preLoaderRoute: typeof BbsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  BbsIdRoute: BbsIdRoute,
  OauthCallbackRoute: OauthCallbackRoute,
  BbsIndexRoute: BbsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
