export const MISSION_PILOT_AGENT_LEASE_MS = 60_000;
export const MISSION_PILOT_QUESTIONNAIRE_RESPONSE_DELAY_MS = 20_000;
export const MISSION_PILOT_MAX_PROVIDER_CALLS_PER_WAKE = 16;
export const MISSION_PILOT_MAX_TOOL_CALLS_PER_WAKE = 32;
export const MISSION_PILOT_MAX_ELAPSED_MS_PER_WAKE = 5 * 60_000;
export const MISSION_PILOT_CONTEXT_SOFT_TOKENS = 24_000;
export const MISSION_PILOT_CONTEXT_HARD_TOKENS = 32_000;
